installCRDs: true

replicaCount: 2

serviceAccount:
  create: true
  name: external-secrets
  annotations: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

webhook:
  replicaCount: 2

certController:
  replicaCount: 2
