fullnameOverride: kube-prometheus-stack

commonLabels:
  app.kubernetes.io/part-of: aws-eks-platform

defaultRules:
  create: true
  rules:
    etcd: false
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

grafana:
  enabled: true
  adminPassword: prom-operator
  defaultDashboardsEnabled: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 2
    retention: 120h
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: platform-null
      group_by:
        - namespace
        - alertname
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
        - receiver: platform-critical-placeholder
          matchers:
            - severity = critical
    receivers:
      - name: platform-null
      - name: platform-critical-placeholder

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 2
    retention: 7d
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
    storageSpec: {}

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
