apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform-application.fullname" . }}
  labels:
    {{- include "platform-application.labels" . | nindent 4 }}
data:
  APP_VERSION: {{ .Chart.AppVersion | quote }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
