{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "platform-application.fullname" . }}-aws-secretsmanager
  labels:
    {{- include "platform-application.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecret.aws.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "platform-application.serviceAccountName" . }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "platform-application.fullname" . }}-runtime
  labels:
    {{- include "platform-application.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ include "platform-application.fullname" . }}-aws-secretsmanager
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
  data:
    {{- range $secretKey, $property := .Values.externalSecret.aws.properties }}
    - secretKey: {{ $secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecret.aws.remoteKey | quote }}
        property: {{ $property | quote }}
    {{- end }}
{{- end }}
