apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  project: platform
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server
      chart: metrics-server
      targetRevision: 3.13.1
      helm:
        releaseName: metrics-server
        valueFiles:
          - $values/platform/metrics-server/values.yaml
    - repoURL: REPLACE_GITHUB_REPOSITORY_URL
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
